version: "3.5"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /home/docker/mongodb/data/db:/data/db
      - type: volume
        source: MONGO_CONFIG
        target: /home/docker/mongodb/data/db:/data/configdb
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - mongo
  wishlist-app:
    build: 
      dockerfile: Dockerfile
      context: .
    image: wishlist-app:latest
    command: ["/wait-for-it.sh", "mongo:27017", "-t", "30", "--", "java", "-jar", "api.jar"]
    container_name: wishlist-app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG

